### PR TITLE
Fixes #97 :Fixed bugged links

### LINKED ISSUE #97: Bugged links

### PR DESCRIPTION
**Pull request by saarthakchats**
Fixes #97

### CODE REVIEW

**Comment by saarthakchats** [comment]
https://saarthakchats.github.io/mysatty2-0-1-2.f-o-s-s-a-s-i-a.o-r-g/

**Comment by saarthakchats** [comment]
In the navbar. There was no Instagram link. Flickr link was added to Instagram icon. I fixed that and added Flickr icon

**Comment by saarthakchats** [comment]
Sorry for closing it. Did it by mistake

**Comment by saarthakchats** [comment]
@harshit98 @vaibhavsingh97 @gabru-md 
Pls review

**Review by harshit98 — APPROVED** [review]

**Pull request merged**
