### PR TITLE
Seperated HTML and CSS

### PR DESCRIPTION
**Pull request by Elgayar**
Solving issue: #24
Live Link: elgayar.github.io/2012.fossasia.org/

### CODE REVIEW

**Comment by Elgayar** [comment]
My live link isn't getting the changes, any ideas why?

**Comment by niccokunzmann** [comment]
Sometimes I need to refresh what is cached. Control+R in Firefox.

**Comment by Elgayar** [comment]
Ohh now it works, DNS wasn't updated or smth..
See the live link, everything works as if it wasn't changed

**Comment by Elgayar** [comment]
@niccokunzmann See if everything's right to you..

**Comment by niccokunzmann** [comment]
The heading in designers.html is different. This may hint at a mistake. What are your thoughts?

http://2012.fossasia.org/designers.html
https://elgayar.github.io/2012.fossasia.org/designers.html

**Comment by Elgayar** [comment]
The only difference I can spot by my eyes is a difference in fonts? @niccokunzmann

**Comment by Elgayar** [comment]
Anyways, I'll make a separate stylesheet for design.html, with it's old styles.

**Comment by Elgayar** [comment]
designers.html*

**Comment by robbyoconnor** [comment]
Why are the anchors not working @Elgayar ?

**Comment by Elgayar** [comment]
I just tested my live link, all the anchors I went through were working, can you specify the page or the section that has an error so that I can debug? @robbyoconnor

**Comment by robbyoconnor** [comment]
If I click About -- it goes to another thing...why?

**Comment by robbyoconnor** [comment]
YOu're going to need to resolve conflicts. I removed the `_site` directory

**Comment by Elgayar** [comment]
I'll open a new Pull Request.

**Comment by Elgayar** [comment]
@robbyoconnor I just have a question, where are the HTML files that I'll be separating the CSS files from?

**Comment by robbyoconnor** [comment]
The html files at the root of the repo.

**Comment by robbyoconnor** [comment]
`_site` is generated by jekyll and should not be checked into git -- ever.

**Comment by Elgayar** [comment]
I'm sorry, this particularly is something new for me... How can I view the root of my repository? I am googling but so far I didn't land on anything useful. @robbyoconnor

**Comment by robbyoconnor** [comment]
You're good -- just update your fork. No need for a new pull request.

Do `git pull --rebase upstream gh-pages`

**Comment by robbyoconnor** [comment]
You're good -- just update your fork. No need for a new pull request.

Do `git pull --rebase upstream gh-pages`

In this case it's what's in the `2012.fossasia.org/` directory -- all those html files. That's the root of the repo. The top-most directory.

**Comment by Elgayar** [comment]
@robbyoconnor I reforked the repo. 
Honestly, I'm kind of confused :D
I also have a question off topic, why did you delete the _site folder? Would that increase the performance?

**Comment by mariobehling** [comment]
@Elgayar Thanks. Your questions are all valid, but in order to keep things flowing, please discuss off-topics in the relevant issues or on one of our chat channels.

Next steps for this pull request: Please follow the steps outlined by @robbyoconnor and update your fork.

Thank you.

**Pull request closed without merging**
