### PR TITLE
Fixes issues in tweet section.

### PR DESCRIPTION
**Pull request by Prashant-Chaurasia**
Fixes : #166

### CODE REVIEW

**Review by vaibhavsingh97 — CHANGES_REQUESTED** [review]
Can you please share live demo link

**Review by akshatnitd — CHANGES_REQUESTED** [review]
I cannot see any changes commited. Please re-check.

Also, provide a demo link so that it can be reviewed

**Comment by adityac8** [comment]
Hey @mariobehling @vaibhavsingh97 @akshatnitd If [this app](https://foss2012.herokuapp.com/) looks fine, should I generate a PR?

**Review by simsausaurabh — COMMENTED** [review]
@Prashant-Chaurasia any updates?

**Comment by mariobehling** [comment]
Was fixed already.

**Pull request closed without merging**
