### PR TITLE
ADDED NAVBAR

### PR DESCRIPTION
**Pull request by samyakbvs**
I have added the navbar and it is similar to the one on the website

### CODE REVIEW

**Comment by samyakbvs** [comment]
@mariobehling 
please see both the issues have been fixed

**Review by isuruAb — COMMENTED** [review]
@samyakbvs  please mention the pertain issue number in the pull request body and title.

**Review by the-codingninja — CHANGES_REQUESTED** [review]
Please resolve the merge conflicts

**Comment by mariobehling** [comment]
Please provide a test link on your Github repository.

**Comment by mariobehling** [comment]
Please also provide a screenshot of the changes.

**Comment by mariobehling** [comment]
Please provide a new PR, if you would like to fix this. Closing this due to inactivity.

**Pull request closed without merging**
