### PR TITLE
Links added

### PR DESCRIPTION
**Pull request by samyakbvs**
The social media links weren't there but added them

### CODE REVIEW

**Comment by anshumanv** [comment]
Thanks for your contribution but I'm able to redirect using links present in the footer by clicking on the fa icons, please provide a deployment for the changes you made and use appropriate PR title.

**Comment by samyakbvs** [comment]
Can you please explain again, I am not able to understand what are you trying to say

**Comment by anshumanv** [comment]
* The links are working for me.
* Please provide a test link where we can see the changes you made.

**Comment by samyakbvs** [comment]
How should I provide a test link

**Comment by samyakbvs** [comment]
Maybe you want this - https://github.com/fossasia/2012.fossasia.org/pull/45/files

**Comment by anshumanv** [comment]
Please follow - http://pages.github.com/
You will learn something amazing today!

**Comment by samyakbvs** [comment]
Were you asking for the link I just sent?

**Comment by anshumanv** [comment]
Nope, please follow the link I provided.

**Comment by samyakbvs** [comment]
okay

**Comment by samyakbvs** [comment]
Umm... Sorry but i still can't figure out that what are you asking for

**Comment by anshumanv** [comment]
Okay, no issues then. :smile: Make sure you understand that later.

But links are perfectly working fine for me, so this isn't needed.

**Comment by harshit98** [comment]
@samyakbvs Provide the screenshot of the fix. I want to see how website looks after doing changes. Also, change the title of the pull request. It is not appropriate. It should be meaningful.

**Review by harshit98 — APPROVED** [review]

**Pull request merged**
