### PR TITLE
Added Documentation Regarding Running in Local Server

### LINKED ISSUE #73: No Documentation regarding Running Locally
No Documentation Regarding Running the Project on the Local Server.

### PR DESCRIPTION
**Pull request by NaviRocker**
Fixes #73 
Added Documentation regarding Running the Project on the Local Server.
Added Live Github Pages Link

### CODE REVIEW

**Comment by mariobehling** [comment]
This is low priority. What we really need is a proper top menu bar as at fossasia.org.

**Comment by anshumanv** [comment]
Also the travis settings have already been merged, please remove that commit.
Try to make this website as close to the orgs website.

**Comment by NaviRocker** [comment]
@mariobehling @anshumanv As this Site is in a Sub Domain of fossasia.org, What if We remove the CSS and JS File in this Site and Link to the Files in Fossasia Main Site.
That way it is easy to make a similar site as that.

**Comment by mariobehling** [comment]
Each repo needs to be self-contained and working by itself.

**Comment by mariobehling** [comment]
We can discuss about a lot of things surely. What is really needed next is to get the top bar menu.

**Comment by NaviRocker** [comment]
Ok sure. I'll work on it and I am closing this because of my fault with commits

**Pull request closed without merging**
