### PR TITLE
Solved Logo and Navigation Bar Issues

### PR DESCRIPTION
**Pull request by Elgayar**
Moved logo to left and implemented same distance between menu items.

Solving Issue: #25

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Is there a live link?

**Comment by Elgayar** [comment]
Yeah! https://elgayar.github.io/2012.fossasia.org/

**Comment by niccokunzmann** [comment]
Is the logo also on the right for you?

**Comment by Elgayar** [comment]
Just fixed it!
Refresh :)

**Comment by niccokunzmann** [comment]
I see ^^

**Comment by Elgayar** [comment]
Thank you very much! <3 @niccokunzmann

**Pull request merged**
