### PR TITLE
Fix sidebar-btn   #189

### LINKED ISSUE #189: Fix sidebar toggle btn
When the user first opens the side bar , his mouse cursor moves  very far away from  the elements he was earlier on and then have to move the mouse a long distance to reach that sidebar toggle button again . 
[Sidebar BUG.mp4.zip](https://github.com/fossasia/2012.fossasia.org/files/2593100/Sidebar.BUG.mp4.zip)

### PR DESCRIPTION
**Pull request by kksinghal**
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- [Preview Link](https://ksninja.github.io/2012.fossasia.org)

- Fixes #189 

## Description / Changes
On every click on the sidebar toggle button , the button itself moves to convenient place and is still under the mouse ' cursor 
See issue #189 for more .

### After:
[Fixed sidebar bug.mp4.zip](https://github.com/fossasia/2012.fossasia.org/files/2593108/Fixed.sidebar.bug.mp4.zip)

- - - - - - - - - - - -

### CODE REVIEW

**Comment by kksinghal** [comment]
Link to the task https://codein.withgoogle.com/dashboard/task-instances/6752965844008960/

**Comment by rcya1** [comment]
@KSNINJA I think your video is bugged, all I can see is this: 
image

The same can be said for the video in issue #189.

From the preview link, upon clicking the side bar, this is what I see:
image
The button overlaps with the FOSSASIA logo, which should be fixed.

Also, when you try to close the sidebar by just clicking the now displaced button, it works fine. However, when you try to close it by just clicking on the main page, the button dissapears.
gif6

**Comment by simarsingh24** [comment]
@KSNINJA  please update the screenshots. Also squash your commits

**Comment by kksinghal** [comment]
@Ryan10145 I have made the changes . Please review again .
For the video , try using VLC media player . I am using mac and extension is different . But that works fine using VLC .

**Pull request closed without merging**
