### PR TITLE
Added Image

### PR DESCRIPTION
**Pull request by arjunpandey2003**
Issue #91

### CODE REVIEW

**Review by sayak119 — COMMENTED** [review]
Can you give a demo link

**Comment by arjunpandey2003** [comment]
https://arjunpandey2003.github.io/2012.fossasiapc.org/.

**Comment by arjunpandey2003** [comment]
@sayak119 done

**Comment by arjunpandey2003** [comment]
@sayak119 can you approve

**Review by sayak119 — APPROVED** [review]

**Review by harshit98 — APPROVED** [review]

**Pull request merged**
