### PR TITLE
Rectify the Links of Sponsors and Partners

### PR DESCRIPTION
**Pull request by neelanshsahai**
Fixes https://github.com/fossasia/2012.fossasia.org/issues/163
Added the Links for the sponsors and the Media Partners.

### CODE REVIEW

**Comment by neelanshsahai** [comment]
@mariobehling I searched a bit but was unable to find the links to the official websites of OSP and LibreGraphics. Can you help?

**Comment by adityac8** [comment]
Hey @neelanshsahai I think OSP is **Open Source Publishing** They have a link on the homepage itself.
**Libre Graphics** doesn't seem to have a website but I think **lgru** is relatable. What do you think @mariobehling ?

**Review by anshumanv — APPROVED** [review]

**Review by akshatnitd — APPROVED** [review]

**Review by simsausaurabh — APPROVED** [review]

**Comment by anshumanv** [comment]
Please fix the conflicts. :smile:

**Review by NaviRocker — APPROVED** [review]

**Review by NaviRocker — CHANGES_REQUESTED** [review]
Resolve Conflicts

**Review by simsausaurabh — CHANGES_REQUESTED** [review]
Please resolve the conflicts :smile:

**Comment by abishekvashok** [comment]
I am gonna close this as someone else, has already done these changes to the repo :)

**Pull request closed without merging**
