### PR TITLE
Improve website styling and documentation Solves #60

### PR DESCRIPTION
**Pull request by kubami9**
## This PR solves issue #60 
 - deleted wrapper and changed background color to white
 - fixed side-bar bug so it doesn't create empty space at the bottom
 - improved documentation
 - added hover effect on social media icons in the footer section

Preview link : https://kubami9.github.io/2012.fossasia.org-kubamichalski-contributing/

### CODE REVIEW

**Comment by anshumanv** [comment]
Changes look neat @kubami9.
Thanks.

**Comment by kubami9** [comment]
Thank you @anshumanv 😃 Do you have any bugs with 2nd point? Now it looks like that 
u_mnie_dziala

**Comment by anshumanv** [comment]
Nicely done, it's clarified now, just saw the site on mobile and this was much needed @kubami9. :smile:

**Review by abishekvashok — APPROVED** [review]

**Comment by mariobehling** [comment]
Ok, thanks. Seems we are back to something similar we had some time ago including your layout fixes. Let's get some major improvements in. Could you help to substitute the header with the FOSSASIA header, please?

**Comment by kubami9** [comment]
@mariobehling okay, I'm ready to work on it as soon as I end working with https://github.com/fossasia/publiccode.asia/issues/68. I'm having some struggles with this task and I wouldn't like to stop other students from contributing by picking all the issues 😄

**Pull request merged**
