### PR TITLE
Made the footer section align correctly

### PR DESCRIPTION
**Pull request by abishekvashok**
The alignation of the footer was broken due to a quick fix by me,
sorry for that. Fixed it here.

Done as followup for task: https://codein.withgoogle.com/dashboard/task-instances/5193904062201856/
Previews: https://abhi2424shek.github.io/2012.fossasia.org

Before screenshots:
image

After screenshots:
image

@mariobehling @jig08 pls review

### CODE REVIEW

**Comment by jigyasa-grover** [comment]
Before and After screenshots pls.

**Comment by abishekvashok** [comment]
@jig08 updated the PR body madam, pls check.

**Comment by mariobehling** [comment]
Good job. Thank you!

**Comment by abishekvashok** [comment]
I would also be pleased if you could review my task too @mariobehling

**Pull request merged**
