### PR TITLE
fixes #56 : dependency removed

### LINKED ISSUE #56: Avoid using external fonts and take out fontawesome.com
For this simple website we want to keep the dependencies low. Therefore please take out external fonts and ensure fonts are working directly from the site.

### PR DESCRIPTION
**Pull request by YashKumarVerma**
removed dependencies.
-font awesome 5
-bootstrap
-jquery

### CODE REVIEW

**Comment by nzec** [comment]
Is it just me or the website looks messed up?

**Review by abishekvashok — CHANGES_REQUESTED** [review]
When you remove dependencies make sure you don't break anything

**Comment by abishekvashok** [comment]
https://YashKumarVerma.github.io/2012.fossasia.org
screenshot from 2017-12-10 21-04-40

**Comment by YashKumarVerma** [comment]
ahh! 😕

**Comment by mariobehling** [comment]
Please provide a new PR, if you have a solution that works. Cheers.

**Pull request closed without merging**
