### PR TITLE
Improving navbar

### PR DESCRIPTION
**Pull request by alejoheredia**
@mariobehling In this PR, I organized and improved the navbar

Preview: https://heredroky.github.io/2012.fossasia.org/

I hope you like it 😄

### CODE REVIEW

**Comment by alejoheredia** [comment]
#10  "Create a dropdown menu with all FOSSASIA events and include FOSSASIA 14/FOSSASIA 15, which are currently on the top bar"

This commit could fix that

**Comment by mariobehling** [comment]
Thanks for the improvements.

**Comment by mariobehling** [comment]
Please link the logo to http://fossasia.org and make the dropdown expand on scroll over. Cheers.

**Comment by mariobehling** [comment]
ok, merging this as work in progress.

**Pull request merged**
