### PR TITLE
Added Navbar according to Fossasia.org

### LINKED ISSUE #38: Add same top menu design as on FOSSASIA main site
FOSSASIA.org has a nice top menu bar. Please add a top menu that has the same design.

### PR DESCRIPTION
**Pull request by NaviRocker**
Fixes #38 
Preview Link - naveentherocker.github.io/2012.fossasia.org/

### CODE REVIEW

**Review by isuruAb — COMMENTED** [review]
it would be nice if we can add the dark logo

**Comment by NaviRocker** [comment]
Well, the Dark Logo was not in the Repo. Shall I add it separately?

**Comment by NaviRocker** [comment]
Done :)

**Review by isuruAb — COMMENTED** [review]
Please squash commits

**Comment by NaviRocker** [comment]
Done @isuruAb

**Review by isuruAb — APPROVED** [review]

**Review by sayak119 — APPROVED** [review]
LGTM

**Review by ParthS007 — APPROVED** [review]

**Pull request merged**
