### PR TITLE
Fixes #93 : Added Map Marker

### LINKED ISSUE #93: Adding location marker

### PR DESCRIPTION
**Pull request by saarthakchats**
Fixes #93 
Added map marker to a location

@0x48piraj helped me in getting the exact geo-location!

### CODE REVIEW

**Review by gabru-md — APPROVED** [review]
Thanks

**Comment by saarthakchats** [comment]
Pls merge thanks

**Comment by saarthakchats** [comment]
@gabru-md @vaibhavsingh97

**Comment by saarthakchats** [comment]
@gabru-md
 No pressure thanks

**Review by the-codingninja — CHANGES_REQUESTED** [review]
Please change PR name to `Fixes #(issue-num): details of fix`
And provide deployment link

**Comment by saarthakchats** [comment]
https://saarthakchats.github.io/s-a-t-t-u-2-0-1-2.fossasia.org/

**Comment by saarthakchats** [comment]
@ms10398 @harshit98 
Done!

**Comment by saarthakchats** [comment]
@vaibhavsingh97

**Review by harshit98 — APPROVED** [review]

**Comment by saarthakchats** [comment]
@harshit98 Also approve my task thanks

**Comment by harshit98** [comment]
I have just saw the Mario's comment. The PR looks to be similar to https://github.com/fossasia/2012.fossasia.org/pull/82. Reverting it back.

**Comment by saarthakchats** [comment]
@harshit98 But his PR didnt add the location.

**Comment by saarthakchats** [comment]
The location is not on the website. My PR did add the map Marker. i think his PR should be reverted instead of mine

**Comment by saarthakchats** [comment]
@harshit98

**Pull request merged**
