### PR TITLE
Added Footer and Header and fixing #51, #30

### LINKED ISSUE #30: Add FOSSASIA footer to all pages
The footer is currently rudimentary and the design broken.

Please implement the FOSSASIA footer on the site.

screenshot from 2017-01-02 15-04-59

### LINKED ISSUE #51: Error with Social Media Logo in Footer
loll

### PR DESCRIPTION
**Pull request by nzec**
* Added Bootstrap
* Updated FontAwesome
* Did tweaks to make the website compatible with Bootstrap
* Added new responsive Footer
* Added new responsive Header
* Kept consistency with the original design.
* Fixes #51 
* Fixes #30 

**Here is the Live link :** https://duttaditya18.github.io/2012.fossasia.org/

I kept in mind all the criticisms from the previous PR and am making this one. 
Please take a look @fossasia/website-admins , @fossasia/web-developers and @mariobehling 

Here is a link to my task : https://codein.withgoogle.com/dashboard/task-instances/5371934252466176/

### CODE REVIEW

**Review by meets2tarun — APPROVED** [review]

**Comment by nzec** [comment]
@meets2tarun Any problems? Or will it be merged?

**Review by mariobehling — CHANGES_REQUESTED** [review]
Please check the following:
* Font and font size changed - should not be
* Space above font size increased for no reason
* Font of footer changed
* Header not matching to FOSSASIA main site

**Comment by nzec** [comment]
@mariobehling Did some changes. Really the best that I can do right here.
Please check this out. Been working on this for quiet a while.

**Comment by mariobehling** [comment]
Thanks. Please check what you can do about the space above the first heading.

screenshot from 2017-12-08 09-58-30

**Comment by nzec** [comment]
@mariobehling I think it should look fine now. Padding

**Comment by nzec** [comment]
@mariobehling Just tell me what is next.

**Comment by mariobehling** [comment]
Please use latest bottom text and address of https://fossasia.org

**Comment by mariobehling** [comment]
Don't claim you are solving #38. You are apparently not solving it.

**Comment by mariobehling** [comment]
It seems like you also changed the gray background color and shadow of main area for no reason. Please keep it lighter as is.

The space above the first heading seems to be gone entirely. Please keep as is in the original version.

screenshot from 2017-12-08 10-26-01

**Comment by nzec** [comment]
@mariobehling Okay. Done all that you just asked.

**Comment by mariobehling** [comment]
Ok, thanks. Keep it up and let's shorten the review process in future by sticking to the issues. Cheers!

**Review by mariobehling — APPROVED** [review]

**Comment by nzec** [comment]
@mariobehling Thank you so much for your help! You see I very new to this community and am still learning. I will surely get better with other people's help. Thanks once again!

**Comment by anshumanv** [comment]
Good Luck! @duttaditya18 

Keep up the learning attitude. :smile:

**Comment by mariobehling** [comment]
While this PR addressed the issues in a good way, it also resulted in some unwanted changes (e.g centering of content, unwanted changes on top menu bar). It can be solved in follow-up issues. I opened some. Would be great if you follow up. Please only change in future what is mentioned in the issue/PR. Cheers.

**Comment by nzec** [comment]
@mariobehling I will surely follow up! Will start working on the issues tomorrow.

**Pull request merged**
