### PR TITLE
ADDED SOME CDNs

### PR DESCRIPTION
**Pull request by samyakbvs**
The reason for these changes is to add a navbar on the website,  so please accept them :)

### CODE REVIEW

**Comment by nzec** [comment]
Do not make a new PR for every commit. Also the buttons are not functioning and #46 added the header before you.

**Comment by samyakbvs** [comment]
The buttons are working fine

**Comment by samyakbvs** [comment]
The header added by #46 is much different from the one on site
and the header added by me is more similar

**Comment by nzec** [comment]
@samyakbvs When you saw I said in the issue that I am doing this task, you shouldn't have started doing it in the first place. And even when you saw my PR, you continued on to do the same task. Exactly why?

And moreover, do not make so PRs for the same thing. Read the rules before starting a task. I have also done the same thing with just one PR.

And you added the buttons after I told you they were not working. Do not lie.

Please try to read the rules from next time.

**Comment by samyakbvs** [comment]
Ya so I never said that my buttons were working before

**Comment by mariobehling** [comment]
There is an issue missing and it is unclear why we need these here specifically. The site should work without CDNs.

**Pull request closed without merging**
