### PR TITLE
Added 404 and 500 Page

### LINKED ISSUE #68: Add 404 and 500 Page

### PR DESCRIPTION
**Pull request by NaviRocker**
Added 404 and 500 Page According to the fossasia.org Style
Preview Link - https://naveentherocker.github.io/2012.fossasia.org/404.html
Preview Link - https://naveentherocker.github.io/2012.fossasia.org/500.html

Fixes #68

### CODE REVIEW

**Review by anshumanv — CHANGES_REQUESTED** [review]
Please make nav dropdowns red on hovering.

**Review by anshumanv — APPROVED** [review]
LGTM

**Comment by the-codingninja** [comment]
Is there any issue which it is related to

**Comment by anshumanv** [comment]
Yes, please open an issue before working on something so you can get input from others.

**Comment by NaviRocker** [comment]
https://github.com/fossasia/2012.fossasia.org/issues/68

**Review by ParthS007 — APPROVED** [review]

**Pull request merged**
