### PR TITLE
add markers

### LINKED ISSUE #185: Place Marker on Map
Place a marker on the Leaflet map.
I am working on this.

### PR DESCRIPTION
**Pull request by pythongiant**
add marker to the map
closes #185 
Preview: https://pythongiant.github.io/2012.fossasia.org/
Map:https://www.openstreetmap.org/export/embed.html?bbox=105.19409179687501%2C9.638661389766769%2C107.29248046875001%2C11.315787392354615&marker=10.045162%2C105.746857&layer=mapnik
screenshot_10

### CODE REVIEW

**Comment by pythongiant** [comment]
@liveHarshit @jogendra @abishekvashok please review

**Review by jogendra — COMMENTED** [review]
Changes looks good but there isn't any sense of working on old projects which are not the priority for now. Also, Please do not submit old repos PR to GCI task, we will reject.

**Comment by pythongiant** [comment]
umm @jogendra this was my GCI task (https://codein.withgoogle.com/dashboard/task-instances/5356785155178496/)

**Comment by jogendra** [comment]
@pythongiant thank you for the info, I was unaware.

**Review by jogendra — APPROVED** [review]

**Review by abishekvashok — APPROVED** [review]

**Pull request merged**
