### PR TITLE
Improved code quality and minified/optimized some js files

### LINKED ISSUE #211: Improve code quality and optimize js
Improve code quality and optimize js

### PR DESCRIPTION
**Pull request by sahilsaha7773**
### Changes done in this pull request:

Improved code quality and minified/optimized some js files which increased the performance of the page.

- [Preview link](https://sahilsaha7773.github.io/2012.fossasia.org/)

- Fixes #211 

### Screenshots (Audits):-

**Befor:**

pb

**After**

pba

-------------------------------------------------

### CODE REVIEW

**Review by saarthakchats — CHANGES_REQUESTED** [review]
Please squash your commits

**Comment by sahilsaha7773** [comment]
@saarthakchats done!!

**Review by sarnava1 — APPROVED** [review]
LGTM. If it is a part of any GCI task then please submit it after it is merged.

**Comment by sahilsaha7773** [comment]
ok sure @sarnava1

**Review by abishekvashok — APPROVED** [review]

**Comment by abishekvashok** [comment]
Thanks

**Comment by sahilsaha7773** [comment]
Thanks!!😊😊

**Pull request merged**
