### PR TITLE
corrected buttons

### PR DESCRIPTION
**Pull request by pratyush1687**
solves #114 
removed the media queries for the button-top class 
before :
image
image
after :
image
image

### CODE REVIEW

**Review by ParthS007 — COMMENTED** [review]
@pratyush1687 Can you please provide a preview link

**Review by isuruAb — COMMENTED** [review]
Awesome, It would be really helpful if you could provide a preview link with your PR.

**Comment by pratyush1687** [comment]
https://pratyush1687.github.io/2012.fossasia.org/

the preview link

**Review by anshumanv — APPROVED** [review]

**Comment by anshumanv** [comment]
Buttons have a little problem in iPhone 5 and 6. Please see.

**Pull request merged**
