### PR TITLE
Background color changed

### PR DESCRIPTION
**Pull request by samyakbvs**
#55 fixed

### CODE REVIEW

**Comment by samyakbvs** [comment]
https://samyakbvs.github.io/samyak-2012.fossasia.org/

**Comment by samyakbvs** [comment]
@mariobehling

**Review by akshatnitd — CHANGES_REQUESTED** [review]
Please resolve the conflicts

**Comment by samyakbvs** [comment]
It isn't showing that what is the conflict

**Comment by samyakbvs** [comment]
closing but i will still be working on the issue

**Pull request closed without merging**
