### PR TITLE
Added Smooth Scroll.

### PR DESCRIPTION
**Pull request by nzec**
* Added Smooth Scroll on internal links.
* Aims to solve #16 

I and Piyush collaborated on this issue.
Take a look @fossasia/website-admins 
Here is the live link : https://duttaditya18.github.io/2012.fossasia.org/
Link to my task : https://codein.withgoogle.com/dashboard/task-instances/6327859486392320/

### CODE REVIEW

**Comment by anshumanv** [comment]
It would be easier for us to test if you can provide a deployment link. :smile:

**Comment by nzec** [comment]
@anshumanv There is the live link above.

**Comment by anshumanv** [comment]
Thanks for editing the PR comment, It wasn't there when you initiated the PR. :smile:

**Comment by nzec** [comment]
I know. Just being cheeky 😄

**Comment by nzec** [comment]
@anshumanv Is it good to go? There was one problem that I saw, but I have now fixed it.

**Review by akshatnitd — CHANGES_REQUESTED** [review]
The problem still persists. Try going to the *Schedule* tab and then clicking the *Home* tab. Now, when you click on *About*, the scrolling is not smooth. Some changes needs to be made on the header links.

**Comment by nzec** [comment]
@akshatnitd @anshumanv Finally managed to fix the problem. Please take a look now.
Here : https://duttaditya18.github.io/2012.fossasia.org

@fossasia/website-admins

**Comment by akshatnitd** [comment]
LGTM!

**Pull request merged**
