### PR TITLE
Scroll over dropdown and linking the logo to fossasia website

### PR DESCRIPTION
**Pull request by alejoheredia**
@mariobehling  Hi! In this commit I did what you told me in #21 

Preview: https://heredroky.github.io/2012.fossasia.org/index.html

Cheers!

### CODE REVIEW

**Comment by mariobehling** [comment]
Thanks. Please ensure the following
* [ ] Create a dropdown menu with _all_ FOSSASIA events 
* [ ] Move the FOSSASIA logo to the left a bit (where the gray area meets the white area). 
screenshot from 2016-12-22 17-59-39

**Comment by alejoheredia** [comment]
@mariobehling How do I have to name the dropdown with all FOSSASIA events? Which events do I have to put in the dropdown?

**Comment by alejoheredia** [comment]
@mariobehling If I move the logo a little bit to the left, this happens
screen shot 2016-12-22 at 12 11 23 pm
😞

**Comment by mariobehling** [comment]
@Heredroky 

> name the dropdown with all FOSSASIA events? 

"FOSSASIA"

> If I move the logo a little bit to the left, this happens

Maybe check CSS class. "Inspect" the element with Chrome tools. Thank you.

**Pull request merged**
