### PR TITLE
FOSSASIA 12's site

### PR DESCRIPTION
**Pull request by akshattripathi**

### CODE REVIEW

**Comment by eMBee** [comment]
the index.html needs to be removed as it covers the index.md file.
the content in some pages is larger than the background: http://akshattripathi.github.io/fossasia12/schedule.html

**Comment by akshattripathi** [comment]
Fixed, however, I didn't get that index.html file part, there is no index.html, only index.md.

**Comment by eMBee** [comment]
this: https://github.com/akshattripathi/fossasia12/blob/gh-pages/index.html
and on http://akshattripathi.github.io/fossasia12/  i don't see the website, but a default page.

**Comment by eMBee** [comment]
it would be nice if the height of the background can match the height of the height of the content

**Comment by akshattripathi** [comment]
Done. :)

**Comment by roonyh** [comment]
Hi! This is a very good opportunity for you to practically use the wisdom you gained from doing that git interactive rebasing task!

For example there are 6 commits messaged "Update index.md". It'll be great if you could combine those into a single commit. You'll probably have to pull those commits to your machine first if you edited the file in the website itself.

And instead of saying just "Update index.md" state what actually you are doing. Most projects that you would work on in future would appreciate conventions of good commit messages and and cleaner commits. So the experience you gain from doing this would be very valuable.

Thanks much!

**Comment by akshattripathi** [comment]
@RoonyH Thank you soooo much for your advice! :+1: It really helped me see a real world usage of git rebase and now the commit history looks a lot cleaner.

Thanks.

**Comment by tradzik** [comment]
@akshattripathi Hello, thank you for your changes! However, it looks you have improperly rebased your pull request  - Github shows only one file has changed. Can you fix that please?

**Comment by akshattripathi** [comment]
@ty221 I don't get it. It shows here that the files are changed: https://github.com/akshattripathi/fossasia12/commit/89232c2ad5c7515cf06101785e2a526de200ecd9.
How do I fix it?

**Comment by tradzik** [comment]
@akshattripathi Please take a look on this pull request - select "Files changed". You'll see just small, minor change to stylesheet.

**Comment by akshattripathi** [comment]
@ty221 Ya, I see that, though, how can I fix it? Make an additional commit?

**Comment by tradzik** [comment]
Yeah, if you really don't like rebasing, please close this pull request and send all your changes again. Thanks! @akshattripathi

**Comment by akshattripathi** [comment]
@ty221 Sorry for the late reply. Now, I would've loved to go back to the commit and then make another commit; however, I don't think I need to. Look at the files:
https://github.com/akshattripathi/fossasia12/tree/gh-pages
They contain the changes desired, so it I don't think that it would be a problem, really.

**Pull request merged**
