### PR TITLE
Removed links as they are already provided in the hamburger :D

### PR DESCRIPTION
**Pull request by yashk0thari**
#140 - I've solved this issue :D

### CODE REVIEW

**Comment by yashk0thari** [comment]
https://beta-king.github.io/Sammy.2012.fossasia.org/ --> Preview Link :D

**Comment by yashk0thari** [comment]
Please review :D

**Review by sayak119 — COMMENTED** [review]
@Beta-King  please mention issue number

**Comment by yashk0thari** [comment]
Issue stated :D

**Review by harshit98 — APPROVED** [review]

**Comment by yashk0thari** [comment]
thank you :D

**Pull request merged**
