### PR TITLE
Footer improvement GCI task

### PR DESCRIPTION
**Pull request by awesometushar000**
https://github.com/fossasia/2012.fossasia.org/issues/42

### CODE REVIEW

**Comment by chashmeetsingh** [comment]
Please share a deployment URL for the changes made.
Thanks!

**Comment by abishekvashok** [comment]
awesometushar000.github.io/2012.fossasia.org

**Comment by akshatnitd** [comment]
@awesometushar000 Kindly share a deployment link. You can refer to https://pages.github.com for deploying using github pages.

**Comment by awesometushar000** [comment]
I have made a different branch as `patch1` and github pages is showing that it can only publish `gh-pages` branch. What shall I do?

**Comment by akshatnitd** [comment]
You can merge the `gh-pages` and `patch1` branch and then deploy it.

**Pull request closed without merging**
