### PR TITLE
Fixing Dropdown Menu Issues

### PR DESCRIPTION
**Pull request by Elgayar**
Solving issue #25

### CODE REVIEW

**Comment by mariobehling** [comment]
Thank you. Please do some minor improvements:
* Align all dropdown items to the left, but indent them (like first three items)
* Ensure on scroll-over whole width is grey

screenshot from 2017-01-03 12-52-48

**Comment by Elgayar** [comment]
Done!! Fixed what you asked for :)
@mariobehling 
image

**Comment by mariobehling** [comment]
Nice work. Thanks.

**Comment by mariobehling** [comment]
Here is a follow up issue, if you like: https://github.com/fossasia/2012.fossasia.org/issues/17

**Pull request merged**
