### PR TITLE
Fixed issue with social links

### PR DESCRIPTION
**Pull request by saarthakchats**
kk
It looked like this.
I have fixed it.

### CODE REVIEW

**Comment by nzec** [comment]
You were supposed to fix the overlapping social links.

**Comment by meets2tarun** [comment]
Provide a test link to your github page for testing.
Refer: https://pages.github.com/

**Comment by saarthakchats** [comment]
I dont know how to give a test link

**Comment by saarthakchats** [comment]
There is nothing on that site

**Comment by saarthakchats** [comment]
Its crap

**Comment by mariobehling** [comment]
It has been solved in the meantime. Thanks.

**Pull request closed without merging**
