### PR TITLE
Fixes#105 Added Link to address

### PR DESCRIPTION
**Pull request by arjunpandey2003**
Fixes issue #105 
Added link to address
Added link to footer.html

### CODE REVIEW

**Review by ParthS007 — CHANGES_REQUESTED** [review]
Please provide a provide link 👍

**Comment by arjunpandey2003** [comment]
https://arjunpandey2003.github.io/2012.fossasiadc.org/.

**Comment by arjunpandey2003** [comment]
@ParthS007 done

**Comment by ParthS007** [comment]
@arjunpandey2003  From next PR, Please follow best practices and provide a better PR message like for this PR you can give `Fixes#105 Added Link to address` as PR title. I hope you now got an idea and please follow this from next PR 👍

**Comment by arjunpandey2003** [comment]
sure
Sorry!

**Review by ParthS007 — APPROVED** [review]

**Comment by arjunpandey2003** [comment]
Could you approve

**Comment by arjunpandey2003** [comment]
Thanks!

**Pull request merged**
