### PR TITLE
Improved quality

### PR DESCRIPTION
**Pull request by arjunpandey2003**
Fixes Issue #101

### CODE REVIEW

**Review by akshatnitd — COMMENTED** [review]
Looks good. I would suggest to solve indent issues of more files and send it in this PR. Also, make sure to squash all commits :)

**Comment by arjunpandey2003** [comment]
@akshatnitd i have made changes to one more file and squashed the commits. Thanks!

**Review by nzec — APPROVED** [review]
Nice Work! 🚀

**Comment by arjunpandey2003** [comment]
@duttaditya18 thanks

**Review by saarthakchats — APPROVED** [review]

**Pull request closed without merging**
