### PR TITLE
Updated Schedule in index.html

### PR DESCRIPTION
**Pull request by Jeewal**
Updated Schedule as In the Linked PDF in index.html of Issue https://github.com/fossasia/2012.fossasia.org/issues/165

### CODE REVIEW

**Comment by Jeewal** [comment]
https://jeewal.github.io/2012.fossasia.org/ @YashKumarVerma

**Review by YashKumarVerma — CHANGES_REQUESTED** [review]
Please squash commits

**Review by abishekvashok — APPROVED** [review]

**Comment by abishekvashok** [comment]
@YashKumarVerma squash and merge.

**Comment by YashKumarVerma** [comment]
> @YashKumarVerma squash and merge.

@abishekvashok  I don't have rights to merge :smile:

**Comment by abishekvashok** [comment]
Task link: https://codein.withgoogle.com/dashboard/task-instances/6139171686055936/

**Pull request merged**
