### PR TITLE
Added Header

### LINKED ISSUE #11: Improve mobile site
Please help to get the mobile site closer to the fossasia.org site:

* [ ] Include a top bar with a fossasia home logo and top right menu icon
screenshot from 2016-12-14 04-33-12
* [ ] Adopt colors and mobile menu items
* [ ] Ensure there are no internal scroll bars

screenshot from 2016-12-14 04-31-15

### PR DESCRIPTION
**Pull request by nzec**
* Added Bootstrap (CSS and JS)
* Added Responsive Header
* Removed old header files.
* Did some tweaks to make sure proper compatibility with Bootstrap.
* Aims to fix #11 entirely.

Piyush helped me in solving this issue.
Here is the live link : https://duttaditya18.github.io/2012.fossasia.org
Please take a look @fossasia/website-admins 
@mariobehling

### CODE REVIEW

**Comment by nzec** [comment]
@anshumanv @harshit98  Please tell me what to be done now. I think I have fixed the problem.

**Comment by isuruAb** [comment]
please mention the corresponding issue number which you are going to solve in the title and the PR body. If there is no any opened issue please open a new one

**Review by isuruAb — COMMENTED** [review]
please mention the corresponding issue number which you are going to solve in the title and the PR body. If there is no any opened issue please open a new one

**Comment by nzec** [comment]
@isuruAb I have done so.

**Comment by nzec** [comment]
@isuruAb Please check it out and tell me what to do. I have been waiting for quiet some time.

**Review by isuruAb — APPROVED** [review]
👍  LGTM

**Review by anshumanv — APPROVED** [review]

**Comment by nzec** [comment]
Merge?

**Comment by nzec** [comment]
Thank you so much for your help!

**Comment by mariobehling** [comment]
Color of links and footer not working as expected anymore. Preview site already shows these errors. @harshit98 Let's keep an eye on this.

@duttaditya18 Please make a new PR improving these. I have to revert this.

**Pull request merged**
